name: Android Build
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            git unzip openjdk-17-jdk \
            python3-pip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libtinfo6 libssl-dev

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.33 virtualenv

      - name: Configure Buildozer (safe initialization)
        run: |
          export PATH=$PATH:~/.local/bin
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          # Ensure minimum required configuration
          echo "[app]
title = MyApp
package.name = myapp
package.domain = org.test
source.dir = .
version = 0.1
requirements = python3,kivy
android.api = 33
android.minapi = 21
android.ndk = 25b" > buildozer.spec

      - name: Build APK
        run: |
          export PATH=$PATH:~/.local/bin
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
          retention-days: 7
          if-no-files-found: error
