name: Android Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: "3.9"
  ANDROID_NDK_VERSION: "25b"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            git unzip openjdk-17-jdk \
            python3-pip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.33

      - name: Configure Buildozer (skip if spec exists)
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
            echo "[app]" >> buildozer.spec
            echo "requirements = python3,kivy" >> buildozer.spec
            echo "android.ndk = $ANDROID_NDK_VERSION" >> buildozer.spec
            echo "android.sdk_path = /usr/local/android-sdk" >> buildozer.spec
          else
            echo "buildozer.spec already exists, skipping initialization"
          fi

      - name: Build APK
        run: |
          export PATH=$PATH:~/.local/bin
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
          retention-days: 5
          if-no-files-found: error
