name: Android Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: "3.9"
  ANDROID_SDK_TOOLS_VERSION: "9477386"  # Version mise à jour (Jan 2024)
  ANDROID_BUILD_TOOLS_VERSION: "34.0.0"
  ANDROID_NDK_VERSION: "25b"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            git unzip openjdk-17-jdk \
            python3-pip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libssl-dev

      - name: Set up Android SDK
        run: |
          # Configuration du SDK Android
          mkdir -p ~/android-sdk
          cd ~/android-sdk
          
          # Téléchargement des command line tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS_VERSION}_latest.zip -O cmdline-tools.zip
          unzip -qq cmdline-tools.zip
          rm cmdline-tools.zip
          
          # Configuration des variables d'environnement
          export ANDROID_SDK_ROOT=~/android-sdk
          export PATH=$PATH:~/android-sdk/cmdline-tools/bin
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "PATH=$PATH" >> $GITHUB_ENV
          
          # Acceptation des licences
          yes | sdkmanager --licenses > /dev/null 2>&1
          
          # Installation des composants SDK
          sdkmanager "platform-tools" "build-tools;$ANDROID_BUILD_TOOLS_VERSION" "platforms;android-34" "ndk;$ANDROID_NDK_VERSION"
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/build-tools/$ANDROID_BUILD_TOOLS_VERSION" >> $GITHUB_PATH

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.33

      - name: Configure Buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          if [ ! -f buildozer.spec ]; then
            buildozer init
            echo "[app]" >> buildozer.spec
            echo "requirements = python3,kivy" >> buildozer.spec
            echo "android.ndk = $ANDROID_NDK_VERSION" >> buildozer.spec
            echo "android.sdk_path = $ANDROID_SDK_ROOT" >> buildozer.spec
            echo "android.build_tools_version = $ANDROID_BUILD_TOOLS_VERSION" >> buildozer.spec
          fi

      - name: Build APK
        run: |
          export PATH=$PATH:~/.local/bin:$ANDROID_SDK_ROOT/build-tools/$ANDROID_BUILD_TOOLS_VERSION
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
          retention-days: 7
          if-no-files-found: error
