name: Android Build
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            git unzip openjdk-17-jdk \
            python3-pip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libtinfo6 libssl-dev

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Buildozer and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.33 virtualenv

      - name: Handle buildozer.spec
        run: |
          export PATH=$PATH:~/.local/bin
          # Ne pas initialiser si le fichier existe déjà
          if [ ! -f buildozer.spec ]; then
            buildozer init
            echo "[app]" > buildozer.spec
            echo "requirements = python3,kivy" >> buildozer.spec
            echo "android.ndk = 25b" >> buildozer.spec
          else
            echo "buildozer.spec exists - using existing configuration"
          fi

      - name: Build APK with Buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
          retention-days: 7
          if-no-files-found: error
