name: Android Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: "3.9"
  ANDROID_SDK_TOOLS_VERSION: "8512546"  # Version mise à jour des outils SDK
  ANDROID_BUILD_TOOLS_VERSION: "34.0.0"  # Version spécifique des build-tools
  ANDROID_NDK_VERSION: "25b"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Augmentation du timeout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            git unzip openjdk-17-jdk \
            python3-pip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libssl-dev

      - name: Set up Android SDK
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          
          # Téléchargement des outils SDK
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS_VERSION}_latest.zip -O cmdline-tools.zip
          unzip -qq cmdline-tools.zip -d /tmp/
          mkdir -p ~/android-sdk/cmdline-tools/latest
          mv /tmp/cmdline-tools/* ~/android-sdk/cmdline-tools/latest/
          rm cmdline-tools.zip
          
          export ANDROID_SDK_ROOT=~/android-sdk
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          
          # Installation des build-tools et platform-tools
          yes | sdkmanager --licenses > /dev/null
          sdkmanager "platform-tools" "build-tools;$ANDROID_BUILD_TOOLS_VERSION" "platforms;android-34"
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/build-tools/$ANDROID_BUILD_TOOLS_VERSION" >> $GITHUB_PATH

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.33

      - name: Configure Buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          if [ ! -f buildozer.spec ]; then
            buildozer init
            echo "[app]" >> buildozer.spec
            echo "requirements = python3,kivy" >> buildozer.spec
            echo "android.ndk = $ANDROID_NDK_VERSION" >> buildozer.spec
            echo "android.sdk_path = $HOME/android-sdk" >> buildozer.spec
            echo "android.build_tools_version = $ANDROID_BUILD_TOOLS_VERSION" >> buildozer.spec
          fi

      - name: Build APK
        run: |
          export PATH=$PATH:~/.local/bin:$HOME/android-sdk/build-tools/$ANDROID_BUILD_TOOLS_VERSION
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
          retention-days: 7
          if-no-files-found: error
